server:
  port: 5000
  servlet:
    context-path: /api


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate:
        show_sql: true

jwt:
  token:
    secret: ${JWT_SECRET}
    expired: ${JWT_EXPIRED}

cloudinary:
  name: ${CLOUDINARY_NAME}
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}